JuliaCIBot complains about missing dependency
ERROR: LoadError: ArgumentError: Package Simplices does not have Distributions in its dependencies. Try to add them to REQUIRE file